//=============================================================================
//
// Code generated by [VAPS XT 4.0.1]
//
//=============================================================================

#ifndef VXTCLSISELLIPSEHASPOLYGONPLUGIN_H
#define VXTCLSISELLIPSEHASPOLYGONPLUGIN_H

//=============================================================================
//                        I N C L U D E   F I L E S
//=============================================================================

#include "sqxQPlugin.h"

#include "vxtClsISEllipseHasPolygon.h"

extern "C" VXTCLSISELLIPSEHASPOLYGON_SPEC sqxQPlugin * sqxQPluginLoad(void); 

extern "C" VXTCLSISELLIPSEHASPOLYGON_SPEC const vxtChar * sqxQPluginProductAPIVersion(void); 


//=============================================================================
//                                C L A S S
//=============================================================================

class VXTCLSISELLIPSEHASPOLYGON_SPEC vxtClsISEllipseHasPolygonPlugin : public sqxQPlugin
{
public:

   vxtClsISEllipseHasPolygonPlugin(const vxtChar *, vxtFloat);

   virtual ~vxtClsISEllipseHasPolygonPlugin();

   virtual vxtBool Initialize(void*);

   virtual void vCleanUp(void*);

   static vxtRTObject* s_pCreateRTObject(const void* a_pInitData);

   static void s_vDeleteRTObject(vxtRTObject* a_pObject);

private:

   // Disallow copy
   vxtClsISEllipseHasPolygonPlugin( const vxtClsISEllipseHasPolygonPlugin& );
   vxtClsISEllipseHasPolygonPlugin& operator=( const vxtClsISEllipseHasPolygonPlugin& );
};


#endif // VXTCLSISELLIPSEHASPOLYGONPLUGIN_H

// END OF FILE

