//=============================================================================
//
// Code generated by [VAPS XT 4.0.1]
//
//=============================================================================

//=============================================================================
//                        I N C L U D E   F I L E S
//=============================================================================

#include "sqxObjPluginFactory.h"

#include "vxtClsISEllipseHasPolygonPlugin.h"

//=====<vxtClsISEllipseHasPolygonPlugin::vxtClsISEllipseHasPolygonPlugin>======
// 
//  Summary: Constructor of the 'vxtClsISEllipseHasPolygonPlugin' class.
// 
//  Return Value: None.
// 
//=============================================================================
vxtClsISEllipseHasPolygonPlugin::vxtClsISEllipseHasPolygonPlugin(const vxtChar *a_pGUIName, vxtFloat a_Priority)
: sqxQPlugin(a_pGUIName, a_Priority)
{
}

//=====<vxtClsISEllipseHasPolygonPlugin::~vxtClsISEllipseHasPolygonPlugin>=====
// 
//  Summary: Destructor of the 'vxtClsISEllipseHasPolygonPlugin' class.
// 
//  Return Value: None.
// 
//=============================================================================
vxtClsISEllipseHasPolygonPlugin::~vxtClsISEllipseHasPolygonPlugin()
{
}

//==============================<sqxQPluginLoad>===============================
// 
//  Summary: The plugin load function, entry point to the plugin dll.
//           Creates a new plugin.
// 
//  Return Value: A pointer to the newly created plugin.
// 
//=============================================================================
sqxQPlugin * sqxQPluginLoad()
{
   return VXT_NEW(vxtClsISEllipseHasPolygonPlugin, (vxtClsISEllipseHasPolygon::CLASS_NAME, 1));
}

//========================<sqxQPluginProductAPIVersion>========================
// 
//  Summary: Retrieves the product API version.
// 
//  Return Value: The product API version string.
// 
//=============================================================================
const vxtChar * sqxQPluginProductAPIVersion()
{
   return SQX_PLUGIN_PRODUCT_API_VERSION;
}

//================<vxtClsISEllipseHasPolygonPlugin::Initialize>================
// 
//  Summary: Called by the plugins loader to initialize the plugin.
// 
//  Return Value: VXT_TRUE or VXT_FALSE.
// 
//=============================================================================
vxtBool vxtClsISEllipseHasPolygonPlugin::Initialize(void* a_pContext)
{
   sqxObjPluginFactory *pFactory = static_cast<sqxObjPluginFactory *>(a_pContext);
   pFactory->SetCreateRTObjFcn(vxtClsISEllipseHasPolygonPlugin::s_pCreateRTObject);
   pFactory->SetDeleteRTObjFcn(vxtClsISEllipseHasPolygonPlugin::s_vDeleteRTObject);
   vxtUShort NumProps;
   const vxtRTProperty *pPropInfo = vxtClsISEllipseHasPolygon::aGetPropInfo(NumProps);
   pFactory->vSetPropInfo(pPropInfo, NumProps);
   const vxtChar *pDepTypeDescr = vxtClsISEllipseHasPolygon::pGetDependentTypesDescriptor();
   pFactory->vSetDependentTypesDescriptor(pDepTypeDescr);
   return VXT_TRUE;
}

//=================<vxtClsISEllipseHasPolygonPlugin::vCleanUp>=================
// 
//  Summary: Called by the plugins loader to clean up the plugin.
// 
//  Return Value: None.
// 
//=============================================================================
void vxtClsISEllipseHasPolygonPlugin::vCleanUp(void*)
{
}

//============<vxtClsISEllipseHasPolygonPlugin::s_pCreateRTObject>=============
// 
//  Summary: Create a RunTime Built Object.
// 
//  Return Value: A pointer to the new RunTime Object.
// 
//=============================================================================
vxtRTObject * vxtClsISEllipseHasPolygonPlugin::s_pCreateRTObject(const void *a_pInitData)
{
   static const vxtBaseClsISEllipseHasPolygon::InitData s_DefaultProps  = {{0.0F, 0.0F}, {0.0F, 0.0F}, {0.0F, 0.0F}, {0.0F, 0.0F}, {0.0F, 0.0F}, 0.0F, 0.0F, VXT_TRUE, 0.0F} ;
   const vxtBaseClsISEllipseHasPolygon::InitData *pInitData = VXT_NULL;

   if (VXT_NULL == a_pInitData)
   {
      pInitData = &s_DefaultProps;
   }
   else
   {
      pInitData = static_cast<const vxtBaseClsISEllipseHasPolygon::InitData*>(a_pInitData);
   }

   return VXT_NEW(vxtClsISEllipseHasPolygon, (*pInitData));
}

//============<vxtClsISEllipseHasPolygonPlugin::s_vDeleteRTObject>=============
// 
//  Summary: Delete a RunTime Built Object.
// 
//  Return Value: None.
// 
//=============================================================================
void vxtClsISEllipseHasPolygonPlugin::s_vDeleteRTObject(vxtRTObject *a_pObject)
{
   VXT_DELETE(a_pObject);
}




// END OF FILE

